### PR TITLE
Add guild support for production

### PR DESCRIPTION
**Pull request by dongle-the-gadget**

### CODE REVIEW

**Comment by dongle-the-gadget** [comment]
@KojiOdyssey I forgot to update the README, can you update it for me? Thanks.

**Comment by KojiOdyssey** [comment]
I can update it. I'm making other small modifications as well.

**Comment by dongle-the-gadget** [comment]
Btw I think specifying `NODE_DEV` would kind of be pointless.

**Comment by KojiOdyssey** [comment]
Alright

**Pull request merged**
